// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RemoteEvent = { "type": "cmdResult", commandId: string, ok: boolean, error?: string | null, };
