// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteCommand } from "./RemoteCommand";

export type RemoteEnvelope = { commandId: string, command: RemoteCommand, };
