// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionActivity } from "./SessionActivity";

/**
 * One row of the mobile session list = SessionMeta essentials + project name.
 */
export type RosterEntry = { sessionId: string, projectId: number, projectName: string, title: string, activity: SessionActivity, lastModified: number, };
