// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryBlock } from "./HistoryBlock";
import type { SessionActivity } from "./SessionActivity";
import type { UsageSummary } from "./UsageSummary";

/**
 * The per-session mirror events the bridge publishes to `abeon-cloud-sess:<id>`.
 * Typed so the mobile app consumes them safely. Wire format is camelCase, `type`-tagged.
 */
export type SessionEvent = { "type": "sessionAppend", sessionId: string, blocks: Array<HistoryBlock>, } | { "type": "sessionActivity", sessionId: string, activity: SessionActivity, } | { "type": "sessionTitle", sessionId: string, title: string, } | { "type": "sessionUsage", sessionId: string, summary: UsageSummary, };
