// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token counts (dimension 1). Cache write collapses 5m+1h for display.
 */
export type TokenTotals = { input: number, output: number, cacheWrite: number, cacheRead: number, };
