// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Action = { id: bigint, projectId: bigint, label: string, command: string, workingDir: string | null, source: string | null, sortOrder: bigint, };
