// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActionPatch = { label: string | null, command: string | null, workingDir: string | null, };
