// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A model alias discovered by `detect_models`, not necessarily in the static
 * `BUILTIN_MODELS` list. `source` is "binary" (scanned from the CLI binary) or
 * "session" (seen in session JSONL fallback).
 */
export type DetectedModel = { modelId: string, family: string, source: string, };
