// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitFile } from "./GitFile";

export type GitStatus = { branch: string | null, ahead: number, behind: number, files: Array<GitFile>, isRepo: boolean, };
