// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PtyKind = { "kind": "claude", session_id: string | null, model: string | null, skip_permissions: boolean, } | { "kind": "action", action_id: number, } | { "kind": "shell" };
