// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelUsage } from "./ModelUsage";
import type { TokenTotals } from "./TokenTotals";

/**
 * Aggregate usage for a session or a whole project (dimension 1 + 2).
 */
export type UsageSummary = { tokens: TokenTotals, costUsd: number, byModel: Array<ModelUsage>, unknownModels: Array<string>, };
