// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider";
import type { SessionActivity } from "./SessionActivity";

export type ActiveSession = { sessionId: string, projectId: number, projectName: string, title: string, activity: SessionActivity, lastModified: number, provider: Provider, };
