// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClickUpTaskRef = { id: string, customId: string | null, name: string, status: string | null, url: string, listName: string | null, };
