// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClickUpProjectConfig = { projectId: number, workspaceId: string, spaceId: string | null, listId: string | null, };
