// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClickUpLink = { projectId: number, taskId: string, customId: string | null, name: string, status: string | null, url: string, linkedAt: number, };
