// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Claude model alias discovered by `detect_claude_options`. `source` is "binary"
 * (scanned from the CLI binary) or "session" (seen in session JSONL fallback).
 * `latest` marks the newest version within its family.
 */
export type DetectedModel = { modelId: string, family: string, source: string, latest: boolean, };
