// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffHunk } from "./DiffHunk";

export type DiffResult = { "kind": "text", hunks: Array<DiffHunk>, } | { "kind": "binary" } | { "kind": "tooLarge", size: number, };
