// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitCommit = { hash: string, shortHash: string, subject: string, author: string, timestamp: number, };
