// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenTotals } from "./TokenTotals";

/**
 * Per-model breakdown (models carry different prices).
 */
export type ModelUsage = { model: string, tokens: TokenTotals, costUsd: number, };
