// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Note = { id: number, projectId: number | null, title: string, content: string, createdAt: number, updatedAt: number, };
