// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RateLimitWindow } from "./RateLimitWindow";

export type ProviderLimits = { shortWindow: RateLimitWindow | null, weekly: RateLimitWindow | null, };
