// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Provider } from "./Provider";

export type PtyKind = { "kind": "agent", provider: Provider, session_id: string | null, model: string | null, skip_permissions: boolean, fresh: boolean, } | { "kind": "action", action_id: number, } | { "kind": "shell" };
