// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RemoteCommand = { "type": "sendPrompt", sessionId: string, text: string, } | { "type": "approvePermission", sessionId: string, } | { "type": "denyPermission", sessionId: string, } | { "type": "stopSession", sessionId: string, } | { "type": "resumeSession", sessionId: string, projectId: number, };
