// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubagentStatus } from "./SubagentStatus";

export type SubagentInfo = { agentId: string, agentType: string, description: string, status: SubagentStatus, startedAt: number, endedAt: number | null, };
